package com.project.zhang.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.project.zhang.entity.FamilyEcnomicRegister01;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAMILY_ECNOMIC_REGISTER01".
*/
public class FamilyEcnomicRegister01Dao extends AbstractDao<FamilyEcnomicRegister01, Long> {

    public static final String TABLENAME = "FAMILY_ECNOMIC_REGISTER01";

    /**
     * Properties of entity FamilyEcnomicRegister01.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Iid = new Property(1, String.class, "iid", false, "IID");
        public final static Property Applicant_id = new Property(2, String.class, "applicant_id", false, "APPLICANT_ID");
        public final static Property Wages_1 = new Property(3, String.class, "wages_1", false, "WAGES_1");
        public final static Property Wages_2 = new Property(4, String.class, "wages_2", false, "WAGES_2");
        public final static Property Wages_3 = new Property(5, String.class, "wages_3", false, "WAGES_3");
        public final static Property Wages_4 = new Property(6, String.class, "wages_4", false, "WAGES_4");
        public final static Property Wages_5 = new Property(7, String.class, "wages_5", false, "WAGES_5");
        public final static Property Wages_6 = new Property(8, String.class, "wages_6", false, "WAGES_6");
        public final static Property Wages_7 = new Property(9, String.class, "wages_7", false, "WAGES_7");
        public final static Property Family_1 = new Property(10, String.class, "family_1", false, "FAMILY_1");
        public final static Property Family_2 = new Property(11, String.class, "family_2", false, "FAMILY_2");
        public final static Property Property_1 = new Property(12, String.class, "property_1", false, "PROPERTY_1");
        public final static Property Property_2 = new Property(13, String.class, "property_2", false, "PROPERTY_2");
        public final static Property Property_3 = new Property(14, String.class, "property_3", false, "PROPERTY_3");
        public final static Property Property_4 = new Property(15, String.class, "property_4", false, "PROPERTY_4");
        public final static Property Property_5 = new Property(16, String.class, "property_5", false, "PROPERTY_5");
        public final static Property Property_6 = new Property(17, String.class, "property_6", false, "PROPERTY_6");
        public final static Property Property_7_1 = new Property(18, String.class, "property_7_1", false, "PROPERTY_7_1");
        public final static Property Property_7_2 = new Property(19, String.class, "property_7_2", false, "PROPERTY_7_2");
        public final static Property Property_7_3 = new Property(20, String.class, "property_7_3", false, "PROPERTY_7_3");
        public final static Property Property_7_4 = new Property(21, String.class, "property_7_4", false, "PROPERTY_7_4");
        public final static Property Property_7_5 = new Property(22, String.class, "property_7_5", false, "PROPERTY_7_5");
        public final static Property Property_7_6 = new Property(23, String.class, "property_7_6", false, "PROPERTY_7_6");
        public final static Property Property_7_7 = new Property(24, String.class, "property_7_7", false, "PROPERTY_7_7");
        public final static Property Property_7_8 = new Property(25, String.class, "property_7_8", false, "PROPERTY_7_8");
        public final static Property Property_7_9 = new Property(26, String.class, "property_7_9", false, "PROPERTY_7_9");
        public final static Property Property_7_10 = new Property(27, String.class, "property_7_10", false, "PROPERTY_7_10");
        public final static Property Transfer_1 = new Property(28, String.class, "transfer_1", false, "TRANSFER_1");
        public final static Property Transfer_2 = new Property(29, String.class, "transfer_2", false, "TRANSFER_2");
        public final static Property Transfer_3 = new Property(30, String.class, "transfer_3", false, "TRANSFER_3");
        public final static Property Transfer_4 = new Property(31, String.class, "transfer_4", false, "TRANSFER_4");
        public final static Property Transfer_5 = new Property(32, String.class, "transfer_5", false, "TRANSFER_5");
        public final static Property Transfer_6 = new Property(33, String.class, "transfer_6", false, "TRANSFER_6");
        public final static Property Transfer_7 = new Property(34, String.class, "transfer_7", false, "TRANSFER_7");
        public final static Property Other_income = new Property(35, String.class, "other_income", false, "OTHER_INCOME");
        public final static Property Subsidy = new Property(36, String.class, "subsidy", false, "SUBSIDY");
    }


    public FamilyEcnomicRegister01Dao(DaoConfig config) {
        super(config);
    }
    
    public FamilyEcnomicRegister01Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAMILY_ECNOMIC_REGISTER01\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IID\" TEXT," + // 1: iid
                "\"APPLICANT_ID\" TEXT," + // 2: applicant_id
                "\"WAGES_1\" TEXT," + // 3: wages_1
                "\"WAGES_2\" TEXT," + // 4: wages_2
                "\"WAGES_3\" TEXT," + // 5: wages_3
                "\"WAGES_4\" TEXT," + // 6: wages_4
                "\"WAGES_5\" TEXT," + // 7: wages_5
                "\"WAGES_6\" TEXT," + // 8: wages_6
                "\"WAGES_7\" TEXT," + // 9: wages_7
                "\"FAMILY_1\" TEXT," + // 10: family_1
                "\"FAMILY_2\" TEXT," + // 11: family_2
                "\"PROPERTY_1\" TEXT," + // 12: property_1
                "\"PROPERTY_2\" TEXT," + // 13: property_2
                "\"PROPERTY_3\" TEXT," + // 14: property_3
                "\"PROPERTY_4\" TEXT," + // 15: property_4
                "\"PROPERTY_5\" TEXT," + // 16: property_5
                "\"PROPERTY_6\" TEXT," + // 17: property_6
                "\"PROPERTY_7_1\" TEXT," + // 18: property_7_1
                "\"PROPERTY_7_2\" TEXT," + // 19: property_7_2
                "\"PROPERTY_7_3\" TEXT," + // 20: property_7_3
                "\"PROPERTY_7_4\" TEXT," + // 21: property_7_4
                "\"PROPERTY_7_5\" TEXT," + // 22: property_7_5
                "\"PROPERTY_7_6\" TEXT," + // 23: property_7_6
                "\"PROPERTY_7_7\" TEXT," + // 24: property_7_7
                "\"PROPERTY_7_8\" TEXT," + // 25: property_7_8
                "\"PROPERTY_7_9\" TEXT," + // 26: property_7_9
                "\"PROPERTY_7_10\" TEXT," + // 27: property_7_10
                "\"TRANSFER_1\" TEXT," + // 28: transfer_1
                "\"TRANSFER_2\" TEXT," + // 29: transfer_2
                "\"TRANSFER_3\" TEXT," + // 30: transfer_3
                "\"TRANSFER_4\" TEXT," + // 31: transfer_4
                "\"TRANSFER_5\" TEXT," + // 32: transfer_5
                "\"TRANSFER_6\" TEXT," + // 33: transfer_6
                "\"TRANSFER_7\" TEXT," + // 34: transfer_7
                "\"OTHER_INCOME\" TEXT," + // 35: other_income
                "\"SUBSIDY\" TEXT);"); // 36: subsidy
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAMILY_ECNOMIC_REGISTER01\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FamilyEcnomicRegister01 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String iid = entity.getIid();
        if (iid != null) {
            stmt.bindString(2, iid);
        }
 
        String applicant_id = entity.getApplicant_id();
        if (applicant_id != null) {
            stmt.bindString(3, applicant_id);
        }
 
        String wages_1 = entity.getWages_1();
        if (wages_1 != null) {
            stmt.bindString(4, wages_1);
        }
 
        String wages_2 = entity.getWages_2();
        if (wages_2 != null) {
            stmt.bindString(5, wages_2);
        }
 
        String wages_3 = entity.getWages_3();
        if (wages_3 != null) {
            stmt.bindString(6, wages_3);
        }
 
        String wages_4 = entity.getWages_4();
        if (wages_4 != null) {
            stmt.bindString(7, wages_4);
        }
 
        String wages_5 = entity.getWages_5();
        if (wages_5 != null) {
            stmt.bindString(8, wages_5);
        }
 
        String wages_6 = entity.getWages_6();
        if (wages_6 != null) {
            stmt.bindString(9, wages_6);
        }
 
        String wages_7 = entity.getWages_7();
        if (wages_7 != null) {
            stmt.bindString(10, wages_7);
        }
 
        String family_1 = entity.getFamily_1();
        if (family_1 != null) {
            stmt.bindString(11, family_1);
        }
 
        String family_2 = entity.getFamily_2();
        if (family_2 != null) {
            stmt.bindString(12, family_2);
        }
 
        String property_1 = entity.getProperty_1();
        if (property_1 != null) {
            stmt.bindString(13, property_1);
        }
 
        String property_2 = entity.getProperty_2();
        if (property_2 != null) {
            stmt.bindString(14, property_2);
        }
 
        String property_3 = entity.getProperty_3();
        if (property_3 != null) {
            stmt.bindString(15, property_3);
        }
 
        String property_4 = entity.getProperty_4();
        if (property_4 != null) {
            stmt.bindString(16, property_4);
        }
 
        String property_5 = entity.getProperty_5();
        if (property_5 != null) {
            stmt.bindString(17, property_5);
        }
 
        String property_6 = entity.getProperty_6();
        if (property_6 != null) {
            stmt.bindString(18, property_6);
        }
 
        String property_7_1 = entity.getProperty_7_1();
        if (property_7_1 != null) {
            stmt.bindString(19, property_7_1);
        }
 
        String property_7_2 = entity.getProperty_7_2();
        if (property_7_2 != null) {
            stmt.bindString(20, property_7_2);
        }
 
        String property_7_3 = entity.getProperty_7_3();
        if (property_7_3 != null) {
            stmt.bindString(21, property_7_3);
        }
 
        String property_7_4 = entity.getProperty_7_4();
        if (property_7_4 != null) {
            stmt.bindString(22, property_7_4);
        }
 
        String property_7_5 = entity.getProperty_7_5();
        if (property_7_5 != null) {
            stmt.bindString(23, property_7_5);
        }
 
        String property_7_6 = entity.getProperty_7_6();
        if (property_7_6 != null) {
            stmt.bindString(24, property_7_6);
        }
 
        String property_7_7 = entity.getProperty_7_7();
        if (property_7_7 != null) {
            stmt.bindString(25, property_7_7);
        }
 
        String property_7_8 = entity.getProperty_7_8();
        if (property_7_8 != null) {
            stmt.bindString(26, property_7_8);
        }
 
        String property_7_9 = entity.getProperty_7_9();
        if (property_7_9 != null) {
            stmt.bindString(27, property_7_9);
        }
 
        String property_7_10 = entity.getProperty_7_10();
        if (property_7_10 != null) {
            stmt.bindString(28, property_7_10);
        }
 
        String transfer_1 = entity.getTransfer_1();
        if (transfer_1 != null) {
            stmt.bindString(29, transfer_1);
        }
 
        String transfer_2 = entity.getTransfer_2();
        if (transfer_2 != null) {
            stmt.bindString(30, transfer_2);
        }
 
        String transfer_3 = entity.getTransfer_3();
        if (transfer_3 != null) {
            stmt.bindString(31, transfer_3);
        }
 
        String transfer_4 = entity.getTransfer_4();
        if (transfer_4 != null) {
            stmt.bindString(32, transfer_4);
        }
 
        String transfer_5 = entity.getTransfer_5();
        if (transfer_5 != null) {
            stmt.bindString(33, transfer_5);
        }
 
        String transfer_6 = entity.getTransfer_6();
        if (transfer_6 != null) {
            stmt.bindString(34, transfer_6);
        }
 
        String transfer_7 = entity.getTransfer_7();
        if (transfer_7 != null) {
            stmt.bindString(35, transfer_7);
        }
 
        String other_income = entity.getOther_income();
        if (other_income != null) {
            stmt.bindString(36, other_income);
        }
 
        String subsidy = entity.getSubsidy();
        if (subsidy != null) {
            stmt.bindString(37, subsidy);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FamilyEcnomicRegister01 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String iid = entity.getIid();
        if (iid != null) {
            stmt.bindString(2, iid);
        }
 
        String applicant_id = entity.getApplicant_id();
        if (applicant_id != null) {
            stmt.bindString(3, applicant_id);
        }
 
        String wages_1 = entity.getWages_1();
        if (wages_1 != null) {
            stmt.bindString(4, wages_1);
        }
 
        String wages_2 = entity.getWages_2();
        if (wages_2 != null) {
            stmt.bindString(5, wages_2);
        }
 
        String wages_3 = entity.getWages_3();
        if (wages_3 != null) {
            stmt.bindString(6, wages_3);
        }
 
        String wages_4 = entity.getWages_4();
        if (wages_4 != null) {
            stmt.bindString(7, wages_4);
        }
 
        String wages_5 = entity.getWages_5();
        if (wages_5 != null) {
            stmt.bindString(8, wages_5);
        }
 
        String wages_6 = entity.getWages_6();
        if (wages_6 != null) {
            stmt.bindString(9, wages_6);
        }
 
        String wages_7 = entity.getWages_7();
        if (wages_7 != null) {
            stmt.bindString(10, wages_7);
        }
 
        String family_1 = entity.getFamily_1();
        if (family_1 != null) {
            stmt.bindString(11, family_1);
        }
 
        String family_2 = entity.getFamily_2();
        if (family_2 != null) {
            stmt.bindString(12, family_2);
        }
 
        String property_1 = entity.getProperty_1();
        if (property_1 != null) {
            stmt.bindString(13, property_1);
        }
 
        String property_2 = entity.getProperty_2();
        if (property_2 != null) {
            stmt.bindString(14, property_2);
        }
 
        String property_3 = entity.getProperty_3();
        if (property_3 != null) {
            stmt.bindString(15, property_3);
        }
 
        String property_4 = entity.getProperty_4();
        if (property_4 != null) {
            stmt.bindString(16, property_4);
        }
 
        String property_5 = entity.getProperty_5();
        if (property_5 != null) {
            stmt.bindString(17, property_5);
        }
 
        String property_6 = entity.getProperty_6();
        if (property_6 != null) {
            stmt.bindString(18, property_6);
        }
 
        String property_7_1 = entity.getProperty_7_1();
        if (property_7_1 != null) {
            stmt.bindString(19, property_7_1);
        }
 
        String property_7_2 = entity.getProperty_7_2();
        if (property_7_2 != null) {
            stmt.bindString(20, property_7_2);
        }
 
        String property_7_3 = entity.getProperty_7_3();
        if (property_7_3 != null) {
            stmt.bindString(21, property_7_3);
        }
 
        String property_7_4 = entity.getProperty_7_4();
        if (property_7_4 != null) {
            stmt.bindString(22, property_7_4);
        }
 
        String property_7_5 = entity.getProperty_7_5();
        if (property_7_5 != null) {
            stmt.bindString(23, property_7_5);
        }
 
        String property_7_6 = entity.getProperty_7_6();
        if (property_7_6 != null) {
            stmt.bindString(24, property_7_6);
        }
 
        String property_7_7 = entity.getProperty_7_7();
        if (property_7_7 != null) {
            stmt.bindString(25, property_7_7);
        }
 
        String property_7_8 = entity.getProperty_7_8();
        if (property_7_8 != null) {
            stmt.bindString(26, property_7_8);
        }
 
        String property_7_9 = entity.getProperty_7_9();
        if (property_7_9 != null) {
            stmt.bindString(27, property_7_9);
        }
 
        String property_7_10 = entity.getProperty_7_10();
        if (property_7_10 != null) {
            stmt.bindString(28, property_7_10);
        }
 
        String transfer_1 = entity.getTransfer_1();
        if (transfer_1 != null) {
            stmt.bindString(29, transfer_1);
        }
 
        String transfer_2 = entity.getTransfer_2();
        if (transfer_2 != null) {
            stmt.bindString(30, transfer_2);
        }
 
        String transfer_3 = entity.getTransfer_3();
        if (transfer_3 != null) {
            stmt.bindString(31, transfer_3);
        }
 
        String transfer_4 = entity.getTransfer_4();
        if (transfer_4 != null) {
            stmt.bindString(32, transfer_4);
        }
 
        String transfer_5 = entity.getTransfer_5();
        if (transfer_5 != null) {
            stmt.bindString(33, transfer_5);
        }
 
        String transfer_6 = entity.getTransfer_6();
        if (transfer_6 != null) {
            stmt.bindString(34, transfer_6);
        }
 
        String transfer_7 = entity.getTransfer_7();
        if (transfer_7 != null) {
            stmt.bindString(35, transfer_7);
        }
 
        String other_income = entity.getOther_income();
        if (other_income != null) {
            stmt.bindString(36, other_income);
        }
 
        String subsidy = entity.getSubsidy();
        if (subsidy != null) {
            stmt.bindString(37, subsidy);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FamilyEcnomicRegister01 readEntity(Cursor cursor, int offset) {
        FamilyEcnomicRegister01 entity = new FamilyEcnomicRegister01( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // iid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // applicant_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // wages_1
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // wages_2
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // wages_3
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // wages_4
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // wages_5
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // wages_6
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // wages_7
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // family_1
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // family_2
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // property_1
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // property_2
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // property_3
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // property_4
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // property_5
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // property_6
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // property_7_1
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // property_7_2
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // property_7_3
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // property_7_4
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // property_7_5
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // property_7_6
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // property_7_7
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // property_7_8
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // property_7_9
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // property_7_10
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // transfer_1
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // transfer_2
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // transfer_3
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // transfer_4
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // transfer_5
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // transfer_6
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // transfer_7
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // other_income
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36) // subsidy
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FamilyEcnomicRegister01 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setApplicant_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setWages_1(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setWages_2(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setWages_3(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWages_4(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setWages_5(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setWages_6(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setWages_7(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setFamily_1(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setFamily_2(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setProperty_1(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setProperty_2(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setProperty_3(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setProperty_4(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setProperty_5(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setProperty_6(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setProperty_7_1(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setProperty_7_2(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setProperty_7_3(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setProperty_7_4(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setProperty_7_5(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setProperty_7_6(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setProperty_7_7(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setProperty_7_8(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setProperty_7_9(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setProperty_7_10(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setTransfer_1(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setTransfer_2(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setTransfer_3(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setTransfer_4(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setTransfer_5(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setTransfer_6(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setTransfer_7(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setOther_income(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setSubsidy(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FamilyEcnomicRegister01 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FamilyEcnomicRegister01 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FamilyEcnomicRegister01 entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
