package com.project.zhang.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.project.zhang.entity.FamilyEcnomicRegister02;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAMILY_ECNOMIC_REGISTER02".
*/
public class FamilyEcnomicRegister02Dao extends AbstractDao<FamilyEcnomicRegister02, Long> {

    public static final String TABLENAME = "FAMILY_ECNOMIC_REGISTER02";

    /**
     * Properties of entity FamilyEcnomicRegister02.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Iid = new Property(1, String.class, "iid", false, "IID");
        public final static Property Applicant_id = new Property(2, String.class, "applicant_id", false, "APPLICANT_ID");
        public final static Property Cash = new Property(3, String.class, "cash", false, "CASH");
        public final static Property Bank_deposit = new Property(4, String.class, "bank_deposit", false, "BANK_DEPOSIT");
        public final static Property Value_security = new Property(5, String.class, "value_security", false, "VALUE_SECURITY");
        public final static Property Car_ship_1 = new Property(6, String.class, "car_ship_1", false, "CAR_SHIP_1");
        public final static Property Car_ship_2 = new Property(7, String.class, "car_ship_2", false, "CAR_SHIP_2");
        public final static Property Car_ship_3 = new Property(8, String.class, "car_ship_3", false, "CAR_SHIP_3");
        public final static Property Car_ship_4 = new Property(9, String.class, "car_ship_4", false, "CAR_SHIP_4");
        public final static Property Car_ship_5 = new Property(10, String.class, "car_ship_5", false, "CAR_SHIP_5");
        public final static Property Car_ship_6 = new Property(11, String.class, "car_ship_6", false, "CAR_SHIP_6");
        public final static Property Car_ship_7 = new Property(12, String.class, "car_ship_7", false, "CAR_SHIP_7");
        public final static Property Big_machine_1 = new Property(13, String.class, "big_machine_1", false, "BIG_MACHINE_1");
        public final static Property Big_machine_2 = new Property(14, String.class, "big_machine_2", false, "BIG_MACHINE_2");
        public final static Property Big_machine_3 = new Property(15, String.class, "big_machine_3", false, "BIG_MACHINE_3");
        public final static Property Big_machine_4 = new Property(16, String.class, "big_machine_4", false, "BIG_MACHINE_4");
        public final static Property Big_machine_5 = new Property(17, String.class, "big_machine_5", false, "BIG_MACHINE_5");
        public final static Property Big_machine_6 = new Property(18, String.class, "big_machine_6", false, "BIG_MACHINE_6");
        public final static Property Big_machine_7 = new Property(19, String.class, "big_machine_7", false, "BIG_MACHINE_7");
        public final static Property House_type = new Property(20, String.class, "house_type", false, "HOUSE_TYPE");
        public final static Property Have_house = new Property(21, String.class, "have_house", false, "HAVE_HOUSE");
        public final static Property House1_1 = new Property(22, String.class, "house1_1", false, "HOUSE1_1");
        public final static Property House1_2 = new Property(23, String.class, "house1_2", false, "HOUSE1_2");
        public final static Property House1_3 = new Property(24, String.class, "house1_3", false, "HOUSE1_3");
        public final static Property House1_4 = new Property(25, String.class, "house1_4", false, "HOUSE1_4");
        public final static Property House1_5 = new Property(26, String.class, "house1_5", false, "HOUSE1_5");
        public final static Property House1_6 = new Property(27, String.class, "house1_6", false, "HOUSE1_6");
        public final static Property House2_1 = new Property(28, String.class, "house2_1", false, "HOUSE2_1");
        public final static Property House2_2 = new Property(29, String.class, "house2_2", false, "HOUSE2_2");
        public final static Property House2_3 = new Property(30, String.class, "house2_3", false, "HOUSE2_3");
        public final static Property House2_4 = new Property(31, String.class, "house2_4", false, "HOUSE2_4");
        public final static Property House2_5 = new Property(32, String.class, "house2_5", false, "HOUSE2_5");
        public final static Property House2_6 = new Property(33, String.class, "house2_6", false, "HOUSE2_6");
        public final static Property House1_lease = new Property(34, String.class, "house1_lease", false, "HOUSE1_LEASE");
        public final static Property House2_lease = new Property(35, String.class, "house2_lease", false, "HOUSE2_LEASE");
        public final static Property House1_structure = new Property(36, String.class, "house1_structure", false, "HOUSE1_STRUCTURE");
        public final static Property House2_structure = new Property(37, String.class, "house2_structure", false, "HOUSE2_STRUCTURE");
        public final static Property Debt_right = new Property(38, String.class, "debt_right", false, "DEBT_RIGHT");
        public final static Property Other_property = new Property(39, String.class, "other_property", false, "OTHER_PROPERTY");
    }


    public FamilyEcnomicRegister02Dao(DaoConfig config) {
        super(config);
    }
    
    public FamilyEcnomicRegister02Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAMILY_ECNOMIC_REGISTER02\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"IID\" TEXT," + // 1: iid
                "\"APPLICANT_ID\" TEXT," + // 2: applicant_id
                "\"CASH\" TEXT," + // 3: cash
                "\"BANK_DEPOSIT\" TEXT," + // 4: bank_deposit
                "\"VALUE_SECURITY\" TEXT," + // 5: value_security
                "\"CAR_SHIP_1\" TEXT," + // 6: car_ship_1
                "\"CAR_SHIP_2\" TEXT," + // 7: car_ship_2
                "\"CAR_SHIP_3\" TEXT," + // 8: car_ship_3
                "\"CAR_SHIP_4\" TEXT," + // 9: car_ship_4
                "\"CAR_SHIP_5\" TEXT," + // 10: car_ship_5
                "\"CAR_SHIP_6\" TEXT," + // 11: car_ship_6
                "\"CAR_SHIP_7\" TEXT," + // 12: car_ship_7
                "\"BIG_MACHINE_1\" TEXT," + // 13: big_machine_1
                "\"BIG_MACHINE_2\" TEXT," + // 14: big_machine_2
                "\"BIG_MACHINE_3\" TEXT," + // 15: big_machine_3
                "\"BIG_MACHINE_4\" TEXT," + // 16: big_machine_4
                "\"BIG_MACHINE_5\" TEXT," + // 17: big_machine_5
                "\"BIG_MACHINE_6\" TEXT," + // 18: big_machine_6
                "\"BIG_MACHINE_7\" TEXT," + // 19: big_machine_7
                "\"HOUSE_TYPE\" TEXT," + // 20: house_type
                "\"HAVE_HOUSE\" TEXT," + // 21: have_house
                "\"HOUSE1_1\" TEXT," + // 22: house1_1
                "\"HOUSE1_2\" TEXT," + // 23: house1_2
                "\"HOUSE1_3\" TEXT," + // 24: house1_3
                "\"HOUSE1_4\" TEXT," + // 25: house1_4
                "\"HOUSE1_5\" TEXT," + // 26: house1_5
                "\"HOUSE1_6\" TEXT," + // 27: house1_6
                "\"HOUSE2_1\" TEXT," + // 28: house2_1
                "\"HOUSE2_2\" TEXT," + // 29: house2_2
                "\"HOUSE2_3\" TEXT," + // 30: house2_3
                "\"HOUSE2_4\" TEXT," + // 31: house2_4
                "\"HOUSE2_5\" TEXT," + // 32: house2_5
                "\"HOUSE2_6\" TEXT," + // 33: house2_6
                "\"HOUSE1_LEASE\" TEXT," + // 34: house1_lease
                "\"HOUSE2_LEASE\" TEXT," + // 35: house2_lease
                "\"HOUSE1_STRUCTURE\" TEXT," + // 36: house1_structure
                "\"HOUSE2_STRUCTURE\" TEXT," + // 37: house2_structure
                "\"DEBT_RIGHT\" TEXT," + // 38: debt_right
                "\"OTHER_PROPERTY\" TEXT);"); // 39: other_property
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAMILY_ECNOMIC_REGISTER02\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FamilyEcnomicRegister02 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String iid = entity.getIid();
        if (iid != null) {
            stmt.bindString(2, iid);
        }
 
        String applicant_id = entity.getApplicant_id();
        if (applicant_id != null) {
            stmt.bindString(3, applicant_id);
        }
 
        String cash = entity.getCash();
        if (cash != null) {
            stmt.bindString(4, cash);
        }
 
        String bank_deposit = entity.getBank_deposit();
        if (bank_deposit != null) {
            stmt.bindString(5, bank_deposit);
        }
 
        String value_security = entity.getValue_security();
        if (value_security != null) {
            stmt.bindString(6, value_security);
        }
 
        String car_ship_1 = entity.getCar_ship_1();
        if (car_ship_1 != null) {
            stmt.bindString(7, car_ship_1);
        }
 
        String car_ship_2 = entity.getCar_ship_2();
        if (car_ship_2 != null) {
            stmt.bindString(8, car_ship_2);
        }
 
        String car_ship_3 = entity.getCar_ship_3();
        if (car_ship_3 != null) {
            stmt.bindString(9, car_ship_3);
        }
 
        String car_ship_4 = entity.getCar_ship_4();
        if (car_ship_4 != null) {
            stmt.bindString(10, car_ship_4);
        }
 
        String car_ship_5 = entity.getCar_ship_5();
        if (car_ship_5 != null) {
            stmt.bindString(11, car_ship_5);
        }
 
        String car_ship_6 = entity.getCar_ship_6();
        if (car_ship_6 != null) {
            stmt.bindString(12, car_ship_6);
        }
 
        String car_ship_7 = entity.getCar_ship_7();
        if (car_ship_7 != null) {
            stmt.bindString(13, car_ship_7);
        }
 
        String big_machine_1 = entity.getBig_machine_1();
        if (big_machine_1 != null) {
            stmt.bindString(14, big_machine_1);
        }
 
        String big_machine_2 = entity.getBig_machine_2();
        if (big_machine_2 != null) {
            stmt.bindString(15, big_machine_2);
        }
 
        String big_machine_3 = entity.getBig_machine_3();
        if (big_machine_3 != null) {
            stmt.bindString(16, big_machine_3);
        }
 
        String big_machine_4 = entity.getBig_machine_4();
        if (big_machine_4 != null) {
            stmt.bindString(17, big_machine_4);
        }
 
        String big_machine_5 = entity.getBig_machine_5();
        if (big_machine_5 != null) {
            stmt.bindString(18, big_machine_5);
        }
 
        String big_machine_6 = entity.getBig_machine_6();
        if (big_machine_6 != null) {
            stmt.bindString(19, big_machine_6);
        }
 
        String big_machine_7 = entity.getBig_machine_7();
        if (big_machine_7 != null) {
            stmt.bindString(20, big_machine_7);
        }
 
        String house_type = entity.getHouse_type();
        if (house_type != null) {
            stmt.bindString(21, house_type);
        }
 
        String have_house = entity.getHave_house();
        if (have_house != null) {
            stmt.bindString(22, have_house);
        }
 
        String house1_1 = entity.getHouse1_1();
        if (house1_1 != null) {
            stmt.bindString(23, house1_1);
        }
 
        String house1_2 = entity.getHouse1_2();
        if (house1_2 != null) {
            stmt.bindString(24, house1_2);
        }
 
        String house1_3 = entity.getHouse1_3();
        if (house1_3 != null) {
            stmt.bindString(25, house1_3);
        }
 
        String house1_4 = entity.getHouse1_4();
        if (house1_4 != null) {
            stmt.bindString(26, house1_4);
        }
 
        String house1_5 = entity.getHouse1_5();
        if (house1_5 != null) {
            stmt.bindString(27, house1_5);
        }
 
        String house1_6 = entity.getHouse1_6();
        if (house1_6 != null) {
            stmt.bindString(28, house1_6);
        }
 
        String house2_1 = entity.getHouse2_1();
        if (house2_1 != null) {
            stmt.bindString(29, house2_1);
        }
 
        String house2_2 = entity.getHouse2_2();
        if (house2_2 != null) {
            stmt.bindString(30, house2_2);
        }
 
        String house2_3 = entity.getHouse2_3();
        if (house2_3 != null) {
            stmt.bindString(31, house2_3);
        }
 
        String house2_4 = entity.getHouse2_4();
        if (house2_4 != null) {
            stmt.bindString(32, house2_4);
        }
 
        String house2_5 = entity.getHouse2_5();
        if (house2_5 != null) {
            stmt.bindString(33, house2_5);
        }
 
        String house2_6 = entity.getHouse2_6();
        if (house2_6 != null) {
            stmt.bindString(34, house2_6);
        }
 
        String house1_lease = entity.getHouse1_lease();
        if (house1_lease != null) {
            stmt.bindString(35, house1_lease);
        }
 
        String house2_lease = entity.getHouse2_lease();
        if (house2_lease != null) {
            stmt.bindString(36, house2_lease);
        }
 
        String house1_structure = entity.getHouse1_structure();
        if (house1_structure != null) {
            stmt.bindString(37, house1_structure);
        }
 
        String house2_structure = entity.getHouse2_structure();
        if (house2_structure != null) {
            stmt.bindString(38, house2_structure);
        }
 
        String debt_right = entity.getDebt_right();
        if (debt_right != null) {
            stmt.bindString(39, debt_right);
        }
 
        String other_property = entity.getOther_property();
        if (other_property != null) {
            stmt.bindString(40, other_property);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FamilyEcnomicRegister02 entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String iid = entity.getIid();
        if (iid != null) {
            stmt.bindString(2, iid);
        }
 
        String applicant_id = entity.getApplicant_id();
        if (applicant_id != null) {
            stmt.bindString(3, applicant_id);
        }
 
        String cash = entity.getCash();
        if (cash != null) {
            stmt.bindString(4, cash);
        }
 
        String bank_deposit = entity.getBank_deposit();
        if (bank_deposit != null) {
            stmt.bindString(5, bank_deposit);
        }
 
        String value_security = entity.getValue_security();
        if (value_security != null) {
            stmt.bindString(6, value_security);
        }
 
        String car_ship_1 = entity.getCar_ship_1();
        if (car_ship_1 != null) {
            stmt.bindString(7, car_ship_1);
        }
 
        String car_ship_2 = entity.getCar_ship_2();
        if (car_ship_2 != null) {
            stmt.bindString(8, car_ship_2);
        }
 
        String car_ship_3 = entity.getCar_ship_3();
        if (car_ship_3 != null) {
            stmt.bindString(9, car_ship_3);
        }
 
        String car_ship_4 = entity.getCar_ship_4();
        if (car_ship_4 != null) {
            stmt.bindString(10, car_ship_4);
        }
 
        String car_ship_5 = entity.getCar_ship_5();
        if (car_ship_5 != null) {
            stmt.bindString(11, car_ship_5);
        }
 
        String car_ship_6 = entity.getCar_ship_6();
        if (car_ship_6 != null) {
            stmt.bindString(12, car_ship_6);
        }
 
        String car_ship_7 = entity.getCar_ship_7();
        if (car_ship_7 != null) {
            stmt.bindString(13, car_ship_7);
        }
 
        String big_machine_1 = entity.getBig_machine_1();
        if (big_machine_1 != null) {
            stmt.bindString(14, big_machine_1);
        }
 
        String big_machine_2 = entity.getBig_machine_2();
        if (big_machine_2 != null) {
            stmt.bindString(15, big_machine_2);
        }
 
        String big_machine_3 = entity.getBig_machine_3();
        if (big_machine_3 != null) {
            stmt.bindString(16, big_machine_3);
        }
 
        String big_machine_4 = entity.getBig_machine_4();
        if (big_machine_4 != null) {
            stmt.bindString(17, big_machine_4);
        }
 
        String big_machine_5 = entity.getBig_machine_5();
        if (big_machine_5 != null) {
            stmt.bindString(18, big_machine_5);
        }
 
        String big_machine_6 = entity.getBig_machine_6();
        if (big_machine_6 != null) {
            stmt.bindString(19, big_machine_6);
        }
 
        String big_machine_7 = entity.getBig_machine_7();
        if (big_machine_7 != null) {
            stmt.bindString(20, big_machine_7);
        }
 
        String house_type = entity.getHouse_type();
        if (house_type != null) {
            stmt.bindString(21, house_type);
        }
 
        String have_house = entity.getHave_house();
        if (have_house != null) {
            stmt.bindString(22, have_house);
        }
 
        String house1_1 = entity.getHouse1_1();
        if (house1_1 != null) {
            stmt.bindString(23, house1_1);
        }
 
        String house1_2 = entity.getHouse1_2();
        if (house1_2 != null) {
            stmt.bindString(24, house1_2);
        }
 
        String house1_3 = entity.getHouse1_3();
        if (house1_3 != null) {
            stmt.bindString(25, house1_3);
        }
 
        String house1_4 = entity.getHouse1_4();
        if (house1_4 != null) {
            stmt.bindString(26, house1_4);
        }
 
        String house1_5 = entity.getHouse1_5();
        if (house1_5 != null) {
            stmt.bindString(27, house1_5);
        }
 
        String house1_6 = entity.getHouse1_6();
        if (house1_6 != null) {
            stmt.bindString(28, house1_6);
        }
 
        String house2_1 = entity.getHouse2_1();
        if (house2_1 != null) {
            stmt.bindString(29, house2_1);
        }
 
        String house2_2 = entity.getHouse2_2();
        if (house2_2 != null) {
            stmt.bindString(30, house2_2);
        }
 
        String house2_3 = entity.getHouse2_3();
        if (house2_3 != null) {
            stmt.bindString(31, house2_3);
        }
 
        String house2_4 = entity.getHouse2_4();
        if (house2_4 != null) {
            stmt.bindString(32, house2_4);
        }
 
        String house2_5 = entity.getHouse2_5();
        if (house2_5 != null) {
            stmt.bindString(33, house2_5);
        }
 
        String house2_6 = entity.getHouse2_6();
        if (house2_6 != null) {
            stmt.bindString(34, house2_6);
        }
 
        String house1_lease = entity.getHouse1_lease();
        if (house1_lease != null) {
            stmt.bindString(35, house1_lease);
        }
 
        String house2_lease = entity.getHouse2_lease();
        if (house2_lease != null) {
            stmt.bindString(36, house2_lease);
        }
 
        String house1_structure = entity.getHouse1_structure();
        if (house1_structure != null) {
            stmt.bindString(37, house1_structure);
        }
 
        String house2_structure = entity.getHouse2_structure();
        if (house2_structure != null) {
            stmt.bindString(38, house2_structure);
        }
 
        String debt_right = entity.getDebt_right();
        if (debt_right != null) {
            stmt.bindString(39, debt_right);
        }
 
        String other_property = entity.getOther_property();
        if (other_property != null) {
            stmt.bindString(40, other_property);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public FamilyEcnomicRegister02 readEntity(Cursor cursor, int offset) {
        FamilyEcnomicRegister02 entity = new FamilyEcnomicRegister02( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // iid
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // applicant_id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // cash
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // bank_deposit
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // value_security
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // car_ship_1
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // car_ship_2
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // car_ship_3
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // car_ship_4
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // car_ship_5
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // car_ship_6
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // car_ship_7
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // big_machine_1
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // big_machine_2
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // big_machine_3
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // big_machine_4
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // big_machine_5
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // big_machine_6
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // big_machine_7
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // house_type
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // have_house
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // house1_1
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // house1_2
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // house1_3
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // house1_4
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // house1_5
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // house1_6
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // house2_1
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // house2_2
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // house2_3
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // house2_4
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // house2_5
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // house2_6
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // house1_lease
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // house2_lease
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // house1_structure
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // house2_structure
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // debt_right
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39) // other_property
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FamilyEcnomicRegister02 entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIid(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setApplicant_id(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCash(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setBank_deposit(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setValue_security(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCar_ship_1(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCar_ship_2(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCar_ship_3(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCar_ship_4(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setCar_ship_5(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCar_ship_6(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCar_ship_7(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setBig_machine_1(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBig_machine_2(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setBig_machine_3(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setBig_machine_4(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setBig_machine_5(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setBig_machine_6(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setBig_machine_7(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setHouse_type(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setHave_house(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setHouse1_1(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setHouse1_2(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setHouse1_3(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setHouse1_4(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setHouse1_5(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setHouse1_6(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setHouse2_1(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setHouse2_2(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setHouse2_3(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setHouse2_4(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setHouse2_5(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setHouse2_6(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setHouse1_lease(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setHouse2_lease(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setHouse1_structure(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setHouse2_structure(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setDebt_right(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setOther_property(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(FamilyEcnomicRegister02 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(FamilyEcnomicRegister02 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FamilyEcnomicRegister02 entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
